### Admin Token: Authorization: Basic YWRtaW46YWRtaW4=
POST http://localhost:4111/api/v1/auth/login
Content-Type: application/json

{
  "username": "Mark1999",
  "password": "Mark85487!"
}

### prerequisites: create user_1 (user-token bWFyazE5OTk6TWFyazg1NDg3IQ==)
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "mark1999",
  "password": "Mark85487!",
  "role": "USER"
}

### prerequisites: create user_2 (user-token QWxsYTIwMDA6QWxsYTg1NDg3IQ==)
POST http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "username": "Alla2000",
  "password": "Alla85487!",
  "role": "USER"
}

### prerequisites: сheck created user_1, user_2 - get all users (=>200)
GET http://localhost:4111/api/v1/admin/users
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

### prerequisites: User_1 create new count (=>200)
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

### prerequisites: User_1 get info about count  (=>200)
GET http://localhost:4111/api/v1/customer/accounts
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

### prerequisites: User_2 create new count (=>200)
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic QWxsYTIwMDA6QWxsYTg1NDg3IQ==

### prerequisites: User_2 get info about count  (=>200)
GET http://localhost:4111/api/v1/customer/accounts
Content-Type: application/json
Authorization: Basic QWxsYTIwMDA6QWxsYTg1NDg3IQ==

### prerequisites: User_2 create second count (=>200)
POST http://localhost:4111/api/v1/accounts
Content-Type: application/json
Authorization: Basic QWxsYTIwMDA6QWxsYTg1NDg3IQ==

### Positive test: User can deposit, count exists (the lower bound of the sum)
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "id": 1,
  "balance": 0.01
}

### Positive test: User can deposit, count exists  (the upper limit of the amount)
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "id": 1,
  "balance": 5000
}

### Positive test: check transaction on the account (amount of the deposit)
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

### Negative test: User can not deposit (count does not exist)
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "id": 200,
  "balance": 100
}

### Negative test: User can not deposit (another user's count)
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "id": 2,
  "balance": 100
}

### Negative test: User can not deposit (negative amount)
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "id": 1,
  "balance": -1
}

### Negative test: User can not deposit (amount=0)
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "id": 1,
  "balance": 0
}

### Negative test: User can not deposit (amount=5000,01)
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "id": 1,
  "balance": 5000.01
}

### Positive test: User can transfer to own account (the lower bound of the sum)
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "senderAccountId": 1,
  "receiverAccountId": 3,
  "amount": 0.01
}

### Positive test: check transaction on the accounts for user_1
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

### Positive test: check transaction on the accounts for user_1
GET http://localhost:4111/api/v1/accounts/3/transactions
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

### Positive test: User can transfer, count exists (the upper limit of the sum)
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "senderAccountId": 1,
  "receiverAccountId": 3,
  "amount": 10000.00
}

### Positive test: User can transfer to another user's account
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 10000.00
}

### Positive test: check transaction on the accounts for user_1
GET http://localhost:4111/api/v1/accounts/1/transactions
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

### Positive test: check transaction on the accounts for user_2
GET http://localhost:4111/api/v1/accounts/2/transactions
Content-Type: application/json
Authorization: Basic QWxsYTIwMDA6QWxsYTg1NDg3IQ==

### Negative test: User can not transfer (amount=10000.01)
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 10000.01
}

### Negative test: User can not transfer (amount=0)
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 0
}

### Negative test: User can not transfer (amount=-1)
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": -1
}

### Negative test: User can not transfer (the amount exceeds the sender's balance)
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "senderAccountId": 1,
  "receiverAccountId": 2,
  "amount": 9000
}

### Negative test: User can not transfer (non-existent account)
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "senderAccountId": 1,
  "receiverAccountId": 299,
  "amount": 9000
}

### Positive test: User can update name (=>200)
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "name": "Mark Samsonov"
}

### Positive test: check new name in profile
GET http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

### Negative test: User can not update name with one word in new name (=>400)
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "name": "Mark1999 dfd dfd "
}

### Negative test: User can not update name with numbers (=>400)
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "name": "Mark1999 Samsonov"
}

### Negative test: User can not update name with special characters (=>400)
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "name": "Mark_Samsonov"
}

### Negative test: empty new name
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "name": ""
}

### Negative test: only spaces in new name
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "name": "   "
}

### Negative test: 3 words in new name
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic bWFyazE5OTk6TWFyazg1NDg3IQ==

{
  "name": "Mark Junior Samsonov"
}
